# Generated by Django 4.1.2 on 2022-12-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
    ]
