# Generated by Django 4.1.2 on 2022-12-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0008_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='contact_no',
        ),
    ]
