# Generated by Django 4.1.2 on 2023-01-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0010_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
