# Generated by Django 4.1.2 on 2023-01-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0011_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
