# Generated by Django 4.1.2 on 2023-01-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0012_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgottoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
