# Generated by Django 4.1.2 on 2023-01-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0013_forgottoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forgottoken',
            new_name='Forgot_token',
        ),
    ]
