# Generated by Django 4.1.2 on 2023-01-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SI', '0015_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
