from django import forms
class Registration(forms.Form):
    username=forms.CharField(max_length=30)
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    gender=forms.CharField(max_length=30)
    date_of_birth=forms.CharField(max_length=30)
    email=forms.EmailField()
    contact_no=forms.IntegerField()
    country=forms.CharField(max_length=30)
    state=forms.CharField(max_length=30)
    city=forms.CharField(max_length=30)
    hobbies=forms.CharField(max_length=30)
    password=forms.CharField(max_length=30)
    confirm_password=forms.CharField(max_length=30)
    upload_avatar=forms.FileField()
